### PR TITLE
Italian translation review

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**

### CODE REVIEW

**Comment by Denisov21** [comment]
Very good, thank @nicolo-ribaudo for correct my errors!

**Comment by nicolo-ribaudo** [comment]
If you merge this, adobe/brackets#11318 can be merged

**Comment by Denisov21** [comment]
I think @nicolo-ribaudo  can close this PR becouse @MarcelGerber merge this PR (https://github.com/adobe/brackets/pull/11117)

**Comment by marcelgerber** [comment]
No, this PR is still relevant and you should still merge it.
adobe#11117 has been merged mid-May, so it included other strings.

**Pull request merged**
